### ISSUE TITLE
Issue in lambda function

### ISSUE THREAD

**Issue by aarts4** [plus3it/terraform-aws-org-new-account-support-case#564]
While running lambda function to test it getting below error:
=================================================
Executing function: failed ([logs ](https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#logStream:group=%252Faws%252Flambda%252Fnew-account-support-case-TGA3pZTs))
Details
The area below shows the last 4 KB of the execution log.
{
  "errorMessage": "'detail'",
  "errorType": "KeyError",
  "stackTrace": [
    "  File \"/var/task/aws_lambda_powertools/logging/logger.py\", line 402, in decorate\n    return lambda_handler(event, context, *args, **kwargs)\n",
    "  File \"/var/task/new_account_support_case.py\", line 156, in lambda_handler\n    account_id = get_account_id(event)\n",
    "  File \"/var/task/new_account_support_case.py\", line 56, in get_account_id\n    event_name = event[\"detail\"][\"eventName\"]\n"
  ]
}

**Comment by lorengordon** [comment]
@aarts4 I can't view the logs in your aws console. But this error is expected if the event used to invoke the Lambda does not have the correct schema. The only events this function supports are CloudTrail events for AWS Organizations, `CreateAccountResult` and `InviteAccountToOrganization`. I haven't seen where the Lambda Console "test" functionality actually includes those test events, so you would have to modify the test event manually in order to get a successful test.
